COMMENT ON COLUMN trips.destination_place_id IS 'Google Places Place ID. 클라이언트는 목적지 이름 대신 이 식별자만 보내고, 서버가 이 값을 기준으로 목적지 정보를 다시 조회한다.';
COMMENT ON COLUMN trips.destination_formatted_address IS '선택한 목적지를 Google Place Details로 조회했을 때 반환된 전체 주소.';
COMMENT ON COLUMN trips.destination_latitude IS 'Google Place Details에서 반환된 목적지 중심 좌표의 위도.';
COMMENT ON COLUMN trips.destination_longitude IS 'Google Place Details에서 반환된 목적지 중심 좌표의 경도.';
COMMENT ON COLUMN trips.destination_viewport_low_latitude IS 'Google Place Details에서 반환된 목적지 검색 영역의 낮은 위도 경계값.';
COMMENT ON COLUMN trips.destination_viewport_low_longitude IS 'Google Place Details에서 반환된 목적지 검색 영역의 낮은 경도 경계값.';
COMMENT ON COLUMN trips.destination_viewport_high_latitude IS 'Google Place Details에서 반환된 목적지 검색 영역의 높은 위도 경계값.';
COMMENT ON COLUMN trips.destination_viewport_high_longitude IS 'Google Place Details에서 반환된 목적지 검색 영역의 높은 경도 경계값.';
COMMENT ON COLUMN trips.destination_types IS '목적지의 Google place type 목록. 후보지 검색 범위를 판단할 때 사용한다.';
COMMENT ON COLUMN trips.destination_primary_type IS 'Google Place Details에서 반환된 목적지의 대표 place type.';

COMMENT ON TABLE trip_planning_profiles IS '여행방 기본 정보와 분리해서 저장하는 여행 상세 설정 테이블.';
COMMENT ON COLUMN trip_planning_profiles.id IS '여행 상세 설정의 기본 키.';
COMMENT ON COLUMN trip_planning_profiles.trip_id IS '상세 설정이 속한 여행방 ID. 여행방 하나에 상세 설정 하나를 저장한다.';
COMMENT ON COLUMN trip_planning_profiles.companion_count IS '방장을 포함한 전체 동행 인원 수.';
COMMENT ON COLUMN trip_planning_profiles.companion_type IS '사용자가 선택한 동행 유형. SOLO, FRIENDS, FAMILY 같은 enum 값을 저장한다.';
COMMENT ON COLUMN trip_planning_profiles.has_children IS '동행자에 어린이가 포함되는지 여부.';
COMMENT ON COLUMN trip_planning_profiles.child_count IS '어린이가 포함된 경우 어린이 인원 수.';
COMMENT ON COLUMN trip_planning_profiles.child_age_group IS '일정 제약에 반영할 어린이 연령대.';
COMMENT ON COLUMN trip_planning_profiles.has_seniors IS '동행자에 시니어가 포함되는지 여부.';
COMMENT ON COLUMN trip_planning_profiles.senior_count IS '시니어가 포함된 경우 시니어 인원 수.';
COMMENT ON COLUMN trip_planning_profiles.currency_code IS '예산 금액에 적용되는 통화 코드.';
COMMENT ON COLUMN trip_planning_profiles.budget_amount IS '사용자가 입력한 선택 예산 금액. null이면 예산 수준만 사용한다.';
COMMENT ON COLUMN trip_planning_profiles.budget_level IS '후보지 수집과 일정 생성에 반영할 예산 수준.';
COMMENT ON COLUMN trip_planning_profiles.included_budget_items IS '예산 금액에 포함되는 항목 목록. enum 이름을 JSON으로 저장한다.';
COMMENT ON COLUMN trip_planning_profiles.travel_pace IS 'RELAXED, BALANCED, PACKED 같은 사용자의 여행 속도.';
COMMENT ON COLUMN trip_planning_profiles.interests IS '사용자가 선택한 관심사 목록. FOOD와 SIGHTSEEING은 기본 후보 카테고리 가중치를 높이는 데 사용한다.';
COMMENT ON COLUMN trip_planning_profiles.primary_transport_mode IS '일정 생성 시 우선 반영할 주 이동수단.';
COMMENT ON COLUMN trip_planning_profiles.secondary_transport_modes IS '일정 생성 시 보조로 허용할 이동수단 목록.';
COMMENT ON COLUMN trip_planning_profiles.accommodation_mode IS '숙소를 아직 정하지 않았는지, 직접 선택했는지 나타내는 입력 방식.';
COMMENT ON COLUMN trip_planning_profiles.accommodation_area IS '숙소를 정하지 않은 경우 사용자가 선호하는 숙소 위치.';
COMMENT ON COLUMN trip_planning_profiles.accommodation_name IS '숙소를 직접 선택한 경우 사용자가 입력한 숙소 이름.';
COMMENT ON COLUMN trip_planning_profiles.check_in_time IS '일정 생성 시 반영할 숙소 체크인 시간.';
COMMENT ON COLUMN trip_planning_profiles.check_out_time IS '일정 생성 시 반영할 숙소 체크아웃 시간.';
COMMENT ON COLUMN trip_planning_profiles.must_visit_places IS '사용자가 꼭 방문하고 싶은 장소명 목록. 최대 5개까지 저장한다.';
COMMENT ON COLUMN trip_planning_profiles.avoid_conditions IS '사용자가 피하고 싶은 일정 조건 목록.';
COMMENT ON COLUMN trip_planning_profiles.free_request IS '사용자가 입력한 자유 요청. 민감할 수 있으므로 로그에 남기지 않는다.';
COMMENT ON COLUMN trip_planning_profiles.created_at IS '여행 상세 설정이 생성된 시각.';
COMMENT ON COLUMN trip_planning_profiles.updated_at IS '여행 상세 설정이 마지막으로 수정된 시각.';

COMMENT ON TABLE itinerary_generations IS '후보지 수집, AI 요청 준비, 일정 저장까지의 생성 흐름을 관리하는 테이블.';
COMMENT ON COLUMN itinerary_generations.id IS '일정 생성 흐름의 기본 키.';
COMMENT ON COLUMN itinerary_generations.trip_id IS '일정 생성을 요청한 여행방 ID.';
COMMENT ON COLUMN itinerary_generations.status IS 'CREATED부터 COMPLETED 또는 FAILED까지 이어지는 일정 생성 상태.';
COMMENT ON COLUMN itinerary_generations.prompt_version IS '수동 전달 프롬프트 또는 향후 OpenAI 요청 생성에 사용한 프롬프트 버전.';
COMMENT ON COLUMN itinerary_generations.failure_reason IS '실패 시 저장하는 안전한 실패 사유. API key나 사용자 자유 요청 같은 민감 정보는 저장하지 않는다.';
COMMENT ON COLUMN itinerary_generations.created_at IS '일정 생성 흐름이 생성된 시각.';
COMMENT ON COLUMN itinerary_generations.updated_at IS '일정 생성 상태가 마지막으로 변경된 시각.';

COMMENT ON TABLE place_candidates IS '하나의 일정 생성 흐름에서 선택된 Google Places 기반 후보지 테이블.';
COMMENT ON COLUMN place_candidates.id IS '저장된 후보지의 기본 키.';
COMMENT ON COLUMN place_candidates.generation_id IS '이 후보지를 수집한 일정 생성 흐름 ID.';
COMMENT ON COLUMN place_candidates.place_id IS '후보지의 Google Places Place ID.';
COMMENT ON COLUMN place_candidates.name IS 'Google Places 응답에서 정규화한 후보지 이름.';
COMMENT ON COLUMN place_candidates.address IS 'Google Places 응답에서 정규화한 후보지 주소 또는 짧은 주소.';
COMMENT ON COLUMN place_candidates.latitude IS 'Google Places 응답에서 받은 후보지 위도.';
COMMENT ON COLUMN place_candidates.longitude IS 'Google Places 응답에서 받은 후보지 경도.';
COMMENT ON COLUMN place_candidates.primary_type IS 'Google Places 응답에서 받은 후보지 대표 place type.';
COMMENT ON COLUMN place_candidates.rating IS '후보지 점수화에 사용하는 Google 평점.';
COMMENT ON COLUMN place_candidates.user_rating_count IS '후보지 점수화에 사용하는 Google 리뷰 수.';
COMMENT ON COLUMN place_candidates.source_categories IS '이 후보지가 발견된 내부 후보 카테고리 목록.';
COMMENT ON COLUMN place_candidates.opening_periods IS 'AI 일정 생성에 전달할 축약된 영업시간 정보.';
COMMENT ON COLUMN place_candidates.score IS '후보지 정렬과 선정을 위해 계산한 내부 점수.';
COMMENT ON COLUMN place_candidates.rank IS '카테고리 quota와 점수를 반영한 최종 후보 순위.';

COMMENT ON TABLE itineraries IS '검증을 통과한 AI 일정 응답을 저장하는 일정 테이블.';
COMMENT ON COLUMN itineraries.id IS '저장된 일정의 기본 키.';
COMMENT ON COLUMN itineraries.trip_id IS '이 일정이 속한 여행방 ID.';
COMMENT ON COLUMN itineraries.generation_id IS '이 일정을 만든 후보지와 AI 응답이 속한 일정 생성 흐름 ID.';
COMMENT ON COLUMN itineraries.summary IS 'AI 응답에서 받은 일정 요약.';
COMMENT ON COLUMN itineraries.created_at IS '일정이 저장된 시각.';

COMMENT ON TABLE itinerary_days IS '저장된 일정을 날짜 단위로 나누는 테이블.';
COMMENT ON COLUMN itinerary_days.id IS '일정 일자의 기본 키.';
COMMENT ON COLUMN itinerary_days.itinerary_id IS '이 일자가 속한 일정 ID.';
COMMENT ON COLUMN itinerary_days.day IS '여행 기간 안에서 1부터 시작하는 일차 번호.';
COMMENT ON COLUMN itinerary_days.date IS '해당 일차의 실제 날짜.';

COMMENT ON TABLE itinerary_items IS '검증된 AI 응답에서 실제 방문 장소 단위로 저장한 일정 항목 테이블.';
COMMENT ON COLUMN itinerary_items.id IS '일정 항목의 기본 키.';
COMMENT ON COLUMN itinerary_items.day_id IS '이 항목이 속한 일정 일자 ID.';
COMMENT ON COLUMN itinerary_items.sequence IS '하루 안에서 방문하는 순서.';
COMMENT ON COLUMN itinerary_items.place_id IS '검증된 후보지에서 가져온 Google Place ID.';
COMMENT ON COLUMN itinerary_items.place_name IS '검증된 후보지에서 가져온 장소 이름.';
COMMENT ON COLUMN itinerary_items.latitude IS '검증된 후보지에서 가져온 위도.';
COMMENT ON COLUMN itinerary_items.longitude IS '검증된 후보지에서 가져온 경도.';
COMMENT ON COLUMN itinerary_items.start_time IS '해당 장소 방문 시작 시간.';
COMMENT ON COLUMN itinerary_items.duration_minutes IS '해당 장소에 머무는 시간. 분 단위로 저장한다.';
COMMENT ON COLUMN itinerary_items.reason IS 'AI가 해당 장소를 일정에 넣은 이유.';
