COMMENT ON COLUMN trips.destination_place_id IS 'Google Places Place ID. Client sends only this identifier; destination snapshot fields are resolved server-side.';
COMMENT ON COLUMN trips.destination_formatted_address IS 'Formatted address returned by Google Place Details for the selected destination.';
COMMENT ON COLUMN trips.destination_latitude IS 'Latitude returned by Google Place Details for the destination center point.';
COMMENT ON COLUMN trips.destination_longitude IS 'Longitude returned by Google Place Details for the destination center point.';
COMMENT ON COLUMN trips.destination_viewport_low_latitude IS 'Southwest or low latitude bound of the destination viewport from Google Place Details.';
COMMENT ON COLUMN trips.destination_viewport_low_longitude IS 'Southwest or low longitude bound of the destination viewport from Google Place Details.';
COMMENT ON COLUMN trips.destination_viewport_high_latitude IS 'Northeast or high latitude bound of the destination viewport from Google Place Details.';
COMMENT ON COLUMN trips.destination_viewport_high_longitude IS 'Northeast or high longitude bound of the destination viewport from Google Place Details.';
COMMENT ON COLUMN trips.destination_types IS 'Google place types for the destination, stored for later candidate search context.';
COMMENT ON COLUMN trips.destination_primary_type IS 'Google primary type for the destination.';

COMMENT ON TABLE trip_planning_profiles IS 'Detailed trip planning input saved separately from the core trip room.';
COMMENT ON COLUMN trip_planning_profiles.id IS 'Primary key of the trip planning profile.';
COMMENT ON COLUMN trip_planning_profiles.trip_id IS 'Trip that owns this planning profile. One profile is stored per trip.';
COMMENT ON COLUMN trip_planning_profiles.companion_count IS 'Total number of travelers including the owner.';
COMMENT ON COLUMN trip_planning_profiles.companion_type IS 'Companion type selected by the user, such as SOLO, FRIENDS, or FAMILY.';
COMMENT ON COLUMN trip_planning_profiles.has_children IS 'Whether child travelers are included.';
COMMENT ON COLUMN trip_planning_profiles.child_count IS 'Number of child travelers when has_children is true.';
COMMENT ON COLUMN trip_planning_profiles.child_age_group IS 'Representative child age group used for itinerary constraints.';
COMMENT ON COLUMN trip_planning_profiles.has_seniors IS 'Whether senior travelers are included.';
COMMENT ON COLUMN trip_planning_profiles.senior_count IS 'Number of senior travelers when has_seniors is true.';
COMMENT ON COLUMN trip_planning_profiles.currency_code IS 'Currency code used for the budget amount.';
COMMENT ON COLUMN trip_planning_profiles.budget_amount IS 'Optional total budget amount. Null means only budget level is used.';
COMMENT ON COLUMN trip_planning_profiles.budget_level IS 'Budget preference level used for candidate and itinerary planning.';
COMMENT ON COLUMN trip_planning_profiles.included_budget_items IS 'Budget categories included in the amount, stored as enum names in JSON.';
COMMENT ON COLUMN trip_planning_profiles.travel_pace IS 'Preferred travel pace such as RELAXED, BALANCED, or PACKED.';
COMMENT ON COLUMN trip_planning_profiles.interests IS 'Selected user interests. FOOD and SIGHTSEEING adjust default candidate category weights.';
COMMENT ON COLUMN trip_planning_profiles.primary_transport_mode IS 'Main transport mode preferred for the itinerary.';
COMMENT ON COLUMN trip_planning_profiles.secondary_transport_modes IS 'Additional transport modes allowed by the user.';
COMMENT ON COLUMN trip_planning_profiles.accommodation_mode IS 'Accommodation input mode, for example undecided or direct place search.';
COMMENT ON COLUMN trip_planning_profiles.accommodation_area IS 'Preferred accommodation area when lodging is not yet decided.';
COMMENT ON COLUMN trip_planning_profiles.accommodation_name IS 'User-provided accommodation name when lodging is selected.';
COMMENT ON COLUMN trip_planning_profiles.check_in_time IS 'Accommodation check-in time used by itinerary planning.';
COMMENT ON COLUMN trip_planning_profiles.check_out_time IS 'Accommodation check-out time used by itinerary planning.';
COMMENT ON COLUMN trip_planning_profiles.must_visit_places IS 'User-entered must-visit place names, maximum five items.';
COMMENT ON COLUMN trip_planning_profiles.avoid_conditions IS 'Conditions or schedule types the user wants to avoid.';
COMMENT ON COLUMN trip_planning_profiles.free_request IS 'Optional free-form request from the user. Do not log this value.';
COMMENT ON COLUMN trip_planning_profiles.created_at IS 'Creation timestamp of the planning profile.';
COMMENT ON COLUMN trip_planning_profiles.updated_at IS 'Last update timestamp of the planning profile.';

COMMENT ON TABLE itinerary_generations IS 'Lifecycle record for collecting candidates, preparing an AI request, and saving an itinerary.';
COMMENT ON COLUMN itinerary_generations.id IS 'Primary key of the itinerary generation.';
COMMENT ON COLUMN itinerary_generations.trip_id IS 'Trip for which this generation was created.';
COMMENT ON COLUMN itinerary_generations.status IS 'Generation lifecycle status from CREATED to COMPLETED or FAILED.';
COMMENT ON COLUMN itinerary_generations.prompt_version IS 'Prompt template version used to build the manual prompt or future OpenAI request.';
COMMENT ON COLUMN itinerary_generations.failure_reason IS 'Safe failure reason code or class name. Sensitive request details are not stored.';
COMMENT ON COLUMN itinerary_generations.created_at IS 'Creation timestamp of the generation.';
COMMENT ON COLUMN itinerary_generations.updated_at IS 'Last status update timestamp of the generation.';

COMMENT ON TABLE place_candidates IS 'Normalized Google Places candidates selected for one itinerary generation.';
COMMENT ON COLUMN place_candidates.id IS 'Primary key of the saved place candidate.';
COMMENT ON COLUMN place_candidates.generation_id IS 'Itinerary generation that owns this candidate.';
COMMENT ON COLUMN place_candidates.place_id IS 'Google Places Place ID for the candidate.';
COMMENT ON COLUMN place_candidates.name IS 'Candidate display name normalized from Google Places.';
COMMENT ON COLUMN place_candidates.address IS 'Candidate formatted or short address from Google Places.';
COMMENT ON COLUMN place_candidates.latitude IS 'Candidate latitude from Google Places.';
COMMENT ON COLUMN place_candidates.longitude IS 'Candidate longitude from Google Places.';
COMMENT ON COLUMN place_candidates.primary_type IS 'Google primary type for the candidate.';
COMMENT ON COLUMN place_candidates.rating IS 'Google rating used as one scoring signal.';
COMMENT ON COLUMN place_candidates.user_rating_count IS 'Google review count used as one scoring signal.';
COMMENT ON COLUMN place_candidates.source_categories IS 'Internal candidate categories where this place was discovered.';
COMMENT ON COLUMN place_candidates.opening_periods IS 'Compact opening hour descriptions used by AI planning when available.';
COMMENT ON COLUMN place_candidates.score IS 'Internal score used to rank candidates for the AI request.';
COMMENT ON COLUMN place_candidates.rank IS 'Final rank after quota and score based selection.';

COMMENT ON TABLE itineraries IS 'Saved itinerary produced from a validated AI itinerary response.';
COMMENT ON COLUMN itineraries.id IS 'Primary key of the itinerary.';
COMMENT ON COLUMN itineraries.trip_id IS 'Trip that owns this itinerary.';
COMMENT ON COLUMN itineraries.generation_id IS 'Generation whose candidates and response produced this itinerary.';
COMMENT ON COLUMN itineraries.summary IS 'Short itinerary summary returned by the AI response.';
COMMENT ON COLUMN itineraries.created_at IS 'Creation timestamp of the saved itinerary.';

COMMENT ON TABLE itinerary_days IS 'Day-level grouping for saved itinerary items.';
COMMENT ON COLUMN itinerary_days.id IS 'Primary key of the itinerary day.';
COMMENT ON COLUMN itinerary_days.itinerary_id IS 'Itinerary that owns this day.';
COMMENT ON COLUMN itinerary_days.day IS 'One-based day number within the trip.';
COMMENT ON COLUMN itinerary_days.date IS 'Calendar date for this itinerary day.';

COMMENT ON TABLE itinerary_items IS 'Place visit item saved after validating the AI response against candidates.';
COMMENT ON COLUMN itinerary_items.id IS 'Primary key of the itinerary item.';
COMMENT ON COLUMN itinerary_items.day_id IS 'Itinerary day that owns this item.';
COMMENT ON COLUMN itinerary_items.sequence IS 'Visit order within the day.';
COMMENT ON COLUMN itinerary_items.place_id IS 'Google Place ID copied from the validated candidate.';
COMMENT ON COLUMN itinerary_items.place_name IS 'Place name copied from the validated candidate.';
COMMENT ON COLUMN itinerary_items.latitude IS 'Latitude copied from the validated candidate.';
COMMENT ON COLUMN itinerary_items.longitude IS 'Longitude copied from the validated candidate.';
COMMENT ON COLUMN itinerary_items.start_time IS 'Planned local start time for this visit.';
COMMENT ON COLUMN itinerary_items.duration_minutes IS 'Planned visit duration in minutes.';
COMMENT ON COLUMN itinerary_items.reason IS 'Short AI-provided reason for selecting this item.';
